package main

import (
	"context"
	"fmt"
	"log"
	"net"
	"sync"
	"time"

	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/reflection"
	"google.golang.org/grpc/status"
)

// ========================================
// Week 16 — Mini-Project: User Service (gRPC Server)
// ========================================
//
// This is the User service in our two-service gRPC application.
// It manages user accounts and is called by:
//   1. The client (directly)
//   2. The Order service (to validate users when creating orders)
//
// Architecture:
//   Client ──> User Service (port 50051)
//   Client ──> Order Service (port 50052) ──> User Service (port 50051)
//
// To run:
//   go run main.go

// ========================================
// Types (normally generated by protoc)
// ========================================

// User represents a user account.
type User struct {
	Id        string `json:"id"`
	Name      string `json:"name"`
	Email     string `json:"email"`
	CreatedAt string `json:"created_at"`
}

// Request/Response types
type CreateUserRequest struct {
	Name  string `json:"name"`
	Email string `json:"email"`
}

type CreateUserResponse struct {
	User *User `json:"user"`
}

type GetUserRequest struct {
	Id string `json:"id"`
}

type GetUserResponse struct {
	User *User `json:"user"`
}

type ListUsersRequest struct{}

type ListUsersResponse struct {
	Users []*User `json:"users"`
}

// ========================================
// Service Implementation
// ========================================

type userServiceServer struct {
	mu      sync.RWMutex
	users   map[string]*User
	counter int
}

func newUserServiceServer() *userServiceServer {
	s := &userServiceServer{
		users: make(map[string]*User),
	}

	// Seed data so the Order service has users to reference
	seedUsers := []struct {
		name  string
		email string
	}{
		{"Alice Johnson", "alice@example.com"},
		{"Bob Smith", "bob@example.com"},
		{"Charlie Brown", "charlie@example.com"},
	}

	for _, u := range seedUsers {
		s.counter++
		id := fmt.Sprintf("user-%03d", s.counter)
		s.users[id] = &User{
			Id:        id,
			Name:      u.name,
			Email:     u.email,
			CreatedAt: time.Now().Format(time.RFC3339),
		}
		log.Printf("Seeded user: %s (%s)", u.name, id)
	}

	return s
}

// CreateUser creates a new user account.
func (s *userServiceServer) CreateUser(ctx context.Context, req *CreateUserRequest) (*CreateUserResponse, error) {
	if req.Name == "" {
		return nil, status.Errorf(codes.InvalidArgument, "name is required")
	}
	if req.Email == "" {
		return nil, status.Errorf(codes.InvalidArgument, "email is required")
	}

	s.mu.Lock()
	defer s.mu.Unlock()

	// Check for duplicate email
	for _, u := range s.users {
		if u.Email == req.Email {
			return nil, status.Errorf(codes.AlreadyExists, "user with email %s already exists", req.Email)
		}
	}

	s.counter++
	id := fmt.Sprintf("user-%03d", s.counter)

	user := &User{
		Id:        id,
		Name:      req.Name,
		Email:     req.Email,
		CreatedAt: time.Now().Format(time.RFC3339),
	}
	s.users[id] = user

	log.Printf("[UserService] Created user: %s (%s, %s)", user.Name, user.Id, user.Email)

	return &CreateUserResponse{User: user}, nil
}

// GetUser retrieves a user by ID.
// This is called by the Order service to validate users.
func (s *userServiceServer) GetUser(ctx context.Context, req *GetUserRequest) (*GetUserResponse, error) {
	if req.Id == "" {
		return nil, status.Errorf(codes.InvalidArgument, "user ID is required")
	}

	s.mu.RLock()
	defer s.mu.RUnlock()

	user, exists := s.users[req.Id]
	if !exists {
		return nil, status.Errorf(codes.NotFound, "user %s not found", req.Id)
	}

	log.Printf("[UserService] Retrieved user: %s (%s)", user.Name, user.Id)

	return &GetUserResponse{User: user}, nil
}

// ListUsers returns all users.
func (s *userServiceServer) ListUsers(ctx context.Context, req *ListUsersRequest) (*ListUsersResponse, error) {
	s.mu.RLock()
	defer s.mu.RUnlock()

	users := make([]*User, 0, len(s.users))
	for _, u := range s.users {
		users = append(users, u)
	}

	log.Printf("[UserService] Listed %d users", len(users))

	return &ListUsersResponse{Users: users}, nil
}

func main() {
	fmt.Println("=== Week 16 Mini-Project: User Service ===")
	fmt.Println()

	// Create the service
	svc := newUserServiceServer()

	// Create listener
	port := ":50051"
	lis, err := net.Listen("tcp", port)
	if err != nil {
		log.Fatalf("Failed to listen on %s: %v", port, err)
	}

	// Create gRPC server with reflection enabled
	// Reflection allows tools like grpcurl to discover services at runtime.
	grpcServer := grpc.NewServer()
	_ = svc // In real code: pb.RegisterUserServiceServer(grpcServer, svc)

	// Enable server reflection for debugging tools
	reflection.Register(grpcServer)

	fmt.Printf("User Service listening on %s\n", port)
	fmt.Println("Seeded users: user-001 (Alice), user-002 (Bob), user-003 (Charlie)")
	fmt.Println()
	fmt.Println("This service provides:")
	fmt.Println("  - CreateUser: Register new users")
	fmt.Println("  - GetUser:    Look up a user (used by Order service)")
	fmt.Println("  - ListUsers:  List all users")
	fmt.Println()
	fmt.Println("Start the Order service next: cd ../order_service && go run main.go")

	if err := grpcServer.Serve(lis); err != nil {
		log.Fatalf("Failed to serve: %v", err)
	}
}
