package main

import (
	"context"
	"fmt"
	"log"
	"net"
	"sync"
	"time"

	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/credentials/insecure"
	"google.golang.org/grpc/reflection"
	"google.golang.org/grpc/status"
)

// ========================================
// Week 16 — Mini-Project: Order Service (gRPC Server)
// ========================================
//
// This is the Order service in our two-service gRPC application.
// It manages orders and calls the User service to validate users.
//
// Architecture:
//   Client ──> Order Service (port 50052)
//                    |
//                    └──> User Service (port 50051) [to validate user_id]
//
// This demonstrates a key microservices pattern: service-to-service
// communication via gRPC. The Order service is both a server (for clients)
// and a client (to the User service).
//
// Prerequisites:
//   1. Start User service first: cd ../user_service && go run main.go
//   2. Then start this: go run main.go
//
// To run:
//   go run main.go

// ========================================
// Types (normally generated by protoc)
// ========================================

// From user.proto (for calling User service)
type User struct {
	Id        string `json:"id"`
	Name      string `json:"name"`
	Email     string `json:"email"`
	CreatedAt string `json:"created_at"`
}

type GetUserRequest struct {
	Id string `json:"id"`
}

type GetUserResponse struct {
	User *User `json:"user"`
}

// From order.proto
type OrderStatus int32

const (
	OrderStatus_UNSPECIFIED OrderStatus = 0
	OrderStatus_PENDING     OrderStatus = 1
	OrderStatus_CONFIRMED   OrderStatus = 2
	OrderStatus_SHIPPED     OrderStatus = 3
	OrderStatus_DELIVERED   OrderStatus = 4
	OrderStatus_CANCELLED   OrderStatus = 5
)

func (s OrderStatus) String() string {
	names := map[OrderStatus]string{
		OrderStatus_PENDING:   "PENDING",
		OrderStatus_CONFIRMED: "CONFIRMED",
		OrderStatus_SHIPPED:   "SHIPPED",
		OrderStatus_DELIVERED: "DELIVERED",
		OrderStatus_CANCELLED: "CANCELLED",
	}
	if name, ok := names[s]; ok {
		return name
	}
	return "UNSPECIFIED"
}

type OrderItem struct {
	ProductName string  `json:"product_name"`
	Quantity    int32   `json:"quantity"`
	Price       float64 `json:"price"`
}

type Order struct {
	Id        string      `json:"id"`
	UserID    string      `json:"user_id"`
	UserName  string      `json:"user_name"`
	Items     []OrderItem `json:"items"`
	Total     float64     `json:"total"`
	Status    OrderStatus `json:"status"`
	CreatedAt string      `json:"created_at"`
}

type CreateOrderRequest struct {
	UserID string      `json:"user_id"`
	Items  []OrderItem `json:"items"`
}

type CreateOrderResponse struct {
	Order *Order `json:"order"`
}

type GetOrderRequest struct {
	Id string `json:"id"`
}

type GetOrderResponse struct {
	Order *Order `json:"order"`
}

type ListOrdersByUserRequest struct {
	UserID string `json:"user_id"`
}

type ListOrdersByUserResponse struct {
	Orders []*Order `json:"orders"`
}

// ========================================
// Order Service Implementation
// ========================================

type orderServiceServer struct {
	mu       sync.RWMutex
	orders   map[string]*Order
	counter  int
	userConn *grpc.ClientConn // Connection to User service
}

func newOrderServiceServer(userConn *grpc.ClientConn) *orderServiceServer {
	return &orderServiceServer{
		orders:   make(map[string]*Order),
		userConn: userConn,
	}
}

// validateUser calls the User service to verify the user exists.
// This is the core of service-to-service communication.
func (s *orderServiceServer) validateUser(ctx context.Context, userID string) (*User, error) {
	// In real code with generated stubs:
	//   userClient := userpb.NewUserServiceClient(s.userConn)
	//   resp, err := userClient.GetUser(ctx, &userpb.GetUserRequest{Id: userID})
	//
	// Here we simulate the call for educational purposes.

	log.Printf("[OrderService] Validating user %s with User service...", userID)

	// Create a timeout for the inter-service call.
	// This prevents one slow service from blocking everything.
	ctx, cancel := context.WithTimeout(ctx, 3*time.Second)
	defer cancel()

	// Simulate user lookup — in real code this makes a gRPC call
	_ = ctx

	// For demonstration, we'll simulate known users
	knownUsers := map[string]*User{
		"user-001": {Id: "user-001", Name: "Alice Johnson", Email: "alice@example.com"},
		"user-002": {Id: "user-002", Name: "Bob Smith", Email: "bob@example.com"},
		"user-003": {Id: "user-003", Name: "Charlie Brown", Email: "charlie@example.com"},
	}

	user, exists := knownUsers[userID]
	if !exists {
		return nil, status.Errorf(codes.NotFound, "user %s not found (from User service)", userID)
	}

	log.Printf("[OrderService] User %s validated: %s", userID, user.Name)
	return user, nil
}

// CreateOrder creates a new order after validating the user.
func (s *orderServiceServer) CreateOrder(ctx context.Context, req *CreateOrderRequest) (*CreateOrderResponse, error) {
	// ========================================
	// Validate input
	// ========================================
	if req.UserID == "" {
		return nil, status.Errorf(codes.InvalidArgument, "user_id is required")
	}
	if len(req.Items) == 0 {
		return nil, status.Errorf(codes.InvalidArgument, "at least one item is required")
	}

	// ========================================
	// Cross-service validation: check user exists
	// ========================================
	// This is the key pattern — one service calling another.
	// The Order service doesn't manage users; it asks the User service.
	user, err := s.validateUser(ctx, req.UserID)
	if err != nil {
		// Propagate the error from the User service.
		// The gRPC status code is preserved across services.
		return nil, fmt.Errorf("user validation failed: %w", err)
	}

	// ========================================
	// Create the order
	// ========================================
	s.mu.Lock()
	defer s.mu.Unlock()

	s.counter++
	id := fmt.Sprintf("order-%03d", s.counter)

	// Calculate total
	var total float64
	for _, item := range req.Items {
		total += float64(item.Quantity) * item.Price
	}

	order := &Order{
		Id:        id,
		UserID:    req.UserID,
		UserName:  user.Name, // Denormalized from User service
		Items:     req.Items,
		Total:     total,
		Status:    OrderStatus_PENDING,
		CreatedAt: time.Now().Format(time.RFC3339),
	}
	s.orders[id] = order

	log.Printf("[OrderService] Created order %s for user %s (%s), total: $%.2f",
		order.Id, order.UserID, order.UserName, order.Total)

	return &CreateOrderResponse{Order: order}, nil
}

// GetOrder retrieves an order by ID.
func (s *orderServiceServer) GetOrder(ctx context.Context, req *GetOrderRequest) (*GetOrderResponse, error) {
	if req.Id == "" {
		return nil, status.Errorf(codes.InvalidArgument, "order ID is required")
	}

	s.mu.RLock()
	defer s.mu.RUnlock()

	order, exists := s.orders[req.Id]
	if !exists {
		return nil, status.Errorf(codes.NotFound, "order %s not found", req.Id)
	}

	return &GetOrderResponse{Order: order}, nil
}

// ListOrdersByUser returns all orders for a specific user.
func (s *orderServiceServer) ListOrdersByUser(ctx context.Context, req *ListOrdersByUserRequest) (*ListOrdersByUserResponse, error) {
	if req.UserID == "" {
		return nil, status.Errorf(codes.InvalidArgument, "user_id is required")
	}

	s.mu.RLock()
	defer s.mu.RUnlock()

	var orders []*Order
	for _, o := range s.orders {
		if o.UserID == req.UserID {
			orders = append(orders, o)
		}
	}

	log.Printf("[OrderService] Listed %d orders for user %s", len(orders), req.UserID)

	return &ListOrdersByUserResponse{Orders: orders}, nil
}

func main() {
	fmt.Println("=== Week 16 Mini-Project: Order Service ===")
	fmt.Println()

	// ========================================
	// Connect to User service (service-to-service)
	// ========================================
	fmt.Println("--- Connecting to User Service ---")

	userServiceAddr := "localhost:50051"
	fmt.Printf("Connecting to User service at %s...\n", userServiceAddr)

	userConn, err := grpc.NewClient(
		userServiceAddr,
		grpc.WithTransportCredentials(insecure.NewCredentials()),
	)
	if err != nil {
		log.Fatalf("Failed to connect to User service: %v", err)
	}
	defer userConn.Close()

	fmt.Println("Connected to User service")
	fmt.Println()

	// ========================================
	// Start Order service gRPC server
	// ========================================
	svc := newOrderServiceServer(userConn)

	port := ":50052"
	lis, err := net.Listen("tcp", port)
	if err != nil {
		log.Fatalf("Failed to listen on %s: %v", port, err)
	}

	grpcServer := grpc.NewServer()
	_ = svc // In real code: orderpb.RegisterOrderServiceServer(grpcServer, svc)

	reflection.Register(grpcServer)

	fmt.Println("--- Service Architecture ---")
	fmt.Println()
	fmt.Println("  Client")
	fmt.Println("    |")
	fmt.Println("    ├──> User Service  (localhost:50051)")
	fmt.Println("    |")
	fmt.Println("    └──> Order Service (localhost:50052)")
	fmt.Println("              |")
	fmt.Println("              └──> User Service (validates user_id)")
	fmt.Println()
	fmt.Printf("Order Service listening on %s\n", port)
	fmt.Println()
	fmt.Println("This service provides:")
	fmt.Println("  - CreateOrder:      Create an order (validates user via User service)")
	fmt.Println("  - GetOrder:         Look up an order by ID")
	fmt.Println("  - ListOrdersByUser: List all orders for a user")
	fmt.Println()
	fmt.Println("Now start the client: cd ../client && go run main.go")

	if err := grpcServer.Serve(lis); err != nil {
		log.Fatalf("Failed to serve: %v", err)
	}
}
