package main

import (
	"context"
	"fmt"
	"log"
	"net"
	"sync"

	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
)

// ========================================
// Week 16 — Lesson 2: gRPC Server
// ========================================
//
// gRPC (Google Remote Procedure Call) is a high-performance RPC framework.
// It uses HTTP/2 for transport and Protocol Buffers for serialization.
//
// This lesson implements a gRPC server for the UserService.
//
// To run:
//   go run main.go
//
// The server listens on port 50051 (the conventional gRPC port).

// ========================================
// Generated types (what protoc would create)
// ========================================
//
// In a real project, these come from running protoc on user.proto.
// We define them inline here for educational purposes.

// UserRole enum
type UserRole int32

const (
	UserRole_UNSPECIFIED UserRole = 0
	UserRole_ADMIN       UserRole = 1
	UserRole_MEMBER      UserRole = 2
	UserRole_GUEST       UserRole = 3
)

// User message
type User struct {
	Id    string   `json:"id"`
	Name  string   `json:"name"`
	Email string   `json:"email"`
	Age   int32    `json:"age"`
	Role  UserRole `json:"role"`
	Tags  []string `json:"tags"`
}

// CreateUserRequest message
type CreateUserRequest struct {
	Name  string   `json:"name"`
	Email string   `json:"email"`
	Age   int32    `json:"age"`
	Role  UserRole `json:"role"`
}

// CreateUserResponse message
type CreateUserResponse struct {
	User *User `json:"user"`
}

// GetUserRequest message
type GetUserRequest struct {
	Id string `json:"id"`
}

// GetUserResponse message
type GetUserResponse struct {
	User *User `json:"user"`
}

// ListUsersRequest message
type ListUsersRequest struct {
	PageSize int32 `json:"page_size"`
}

// ========================================
// Service Interface (what protoc-gen-go-grpc generates)
// ========================================
//
// protoc-gen-go-grpc generates an interface that your server must implement.
// It also generates a registration function to plug your implementation
// into the gRPC server.

// UserServiceServer is the interface generated by protoc-gen-go-grpc.
// Your server implementation must satisfy this interface.
//
// In real generated code, there's also an UnimplementedUserServiceServer
// that provides default implementations returning "unimplemented" errors.
// You embed it in your server struct for forward compatibility.
type UserServiceServer interface {
	CreateUser(ctx context.Context, req *CreateUserRequest) (*CreateUserResponse, error)
	GetUser(ctx context.Context, req *GetUserRequest) (*GetUserResponse, error)
	// ListUsers is a server-streaming RPC.
	// Instead of returning a single response, it uses a stream to send
	// multiple GetUserResponse messages back to the client.
	ListUsers(req *ListUsersRequest, stream grpc.ServerStream) error
}

// ========================================
// Server Implementation
// ========================================

// userServer is our implementation of the UserService.
// It stores users in memory with a mutex for thread safety.
type userServer struct {
	mu      sync.RWMutex
	users   map[string]*User
	counter int
}

// newUserServer creates a server with some seed data.
func newUserServer() *userServer {
	s := &userServer{
		users:   make(map[string]*User),
		counter: 0,
	}

	// Seed with some initial users
	seedUsers := []struct {
		name  string
		email string
		age   int32
		role  UserRole
	}{
		{"Alice Johnson", "alice@example.com", 30, UserRole_ADMIN},
		{"Bob Smith", "bob@example.com", 25, UserRole_MEMBER},
		{"Charlie Brown", "charlie@example.com", 35, UserRole_MEMBER},
		{"Diana Prince", "diana@example.com", 28, UserRole_GUEST},
	}

	for _, u := range seedUsers {
		s.counter++
		id := fmt.Sprintf("user-%03d", s.counter)
		s.users[id] = &User{
			Id:    id,
			Name:  u.name,
			Email: u.email,
			Age:   u.age,
			Role:  u.role,
		}
	}

	return s
}

// CreateUser implements the CreateUser RPC.
// This is a unary RPC: one request in, one response out.
func (s *userServer) CreateUser(ctx context.Context, req *CreateUserRequest) (*CreateUserResponse, error) {
	// ========================================
	// Input validation — always validate in your RPCs!
	// ========================================
	if req.Name == "" {
		// Use gRPC status codes for errors, not plain errors.
		// Common codes: InvalidArgument, NotFound, AlreadyExists,
		// PermissionDenied, Internal, Unavailable, etc.
		return nil, status.Errorf(codes.InvalidArgument, "name is required")
	}
	if req.Email == "" {
		return nil, status.Errorf(codes.InvalidArgument, "email is required")
	}

	// ========================================
	// Context checking — respect cancellation
	// ========================================
	// The context carries deadlines, cancellation signals, and metadata.
	// Always check if the client has cancelled the request.
	if ctx.Err() != nil {
		return nil, status.Errorf(codes.Cancelled, "request cancelled by client")
	}

	// ========================================
	// Business logic
	// ========================================
	s.mu.Lock()
	defer s.mu.Unlock()

	s.counter++
	id := fmt.Sprintf("user-%03d", s.counter)

	user := &User{
		Id:    id,
		Name:  req.Name,
		Email: req.Email,
		Age:   req.Age,
		Role:  req.Role,
	}

	s.users[id] = user
	log.Printf("Created user: %s (%s)", user.Name, user.Id)

	return &CreateUserResponse{User: user}, nil
}

// GetUser implements the GetUser RPC.
// Another unary RPC demonstrating error handling with gRPC status codes.
func (s *userServer) GetUser(ctx context.Context, req *GetUserRequest) (*GetUserResponse, error) {
	if req.Id == "" {
		return nil, status.Errorf(codes.InvalidArgument, "user ID is required")
	}

	s.mu.RLock()
	defer s.mu.RUnlock()

	user, exists := s.users[req.Id]
	if !exists {
		// NotFound is the appropriate status code when a resource doesn't exist.
		return nil, status.Errorf(codes.NotFound, "user %s not found", req.Id)
	}

	log.Printf("Retrieved user: %s (%s)", user.Name, user.Id)
	return &GetUserResponse{User: user}, nil
}

// ListUsers implements the ListUsers server-streaming RPC.
//
// Server streaming means:
//   - Client sends ONE request
//   - Server sends MULTIPLE responses over the stream
//   - Server calls stream.Send() for each response
//   - When the function returns, the stream is closed
//
// In real generated code, the stream parameter would be a typed
// UserService_ListUsersServer interface with a Send(*GetUserResponse) method.
func (s *userServer) ListUsers(req *ListUsersRequest, stream grpc.ServerStream) error {
	s.mu.RLock()
	defer s.mu.RUnlock()

	log.Printf("Streaming %d users to client", len(s.users))

	count := 0
	for _, user := range s.users {
		// Check if the client has cancelled
		if stream.Context().Err() != nil {
			return status.Errorf(codes.Cancelled, "client disconnected")
		}

		// In real code, you'd use the typed Send method:
		//   stream.Send(&GetUserResponse{User: user})
		// Here we just log to demonstrate the concept
		resp := &GetUserResponse{User: user}
		_ = resp // Would be sent via stream.Send()

		log.Printf("  Streaming user: %s (%s)", user.Name, user.Id)
		count++

		// Respect page size if specified
		if req.PageSize > 0 && int32(count) >= req.PageSize {
			break
		}
	}

	log.Printf("Finished streaming %d users", count)
	return nil
}

func main() {
	fmt.Println("=== Week 16, Lesson 2: gRPC Server ===")
	fmt.Println()

	// ========================================
	// Step 1: Create a TCP listener
	// ========================================
	// gRPC servers listen on a TCP port.
	// Port 50051 is the conventional default for gRPC.
	port := ":50051"
	lis, err := net.Listen("tcp", port)
	if err != nil {
		log.Fatalf("Failed to listen on %s: %v", port, err)
	}

	// ========================================
	// Step 2: Create a gRPC server
	// ========================================
	// grpc.NewServer() creates a new gRPC server.
	// You can pass options for things like:
	//   - Interceptors (middleware for RPCs)
	//   - TLS credentials
	//   - Max message sizes
	//   - Keepalive settings

	grpcServer := grpc.NewServer(
		// Example options (uncomment to use):
		// grpc.MaxRecvMsgSize(1024 * 1024 * 10),  // 10MB max receive
		// grpc.MaxSendMsgSize(1024 * 1024 * 10),  // 10MB max send
	)

	// ========================================
	// Step 3: Register your service implementation
	// ========================================
	// In real code with protoc-generated files, you'd call:
	//   pb.RegisterUserServiceServer(grpcServer, newUserServer())
	//
	// This tells the gRPC server which methods are available
	// and which implementation to call.

	server := newUserServer()
	_ = server // In real code: pb.RegisterUserServiceServer(grpcServer, server)

	fmt.Println("--- gRPC Server Architecture ---")
	fmt.Println()
	fmt.Println("  Client Request")
	fmt.Println("       |")
	fmt.Println("       v")
	fmt.Println("  [TCP Listener] (port 50051)")
	fmt.Println("       |")
	fmt.Println("       v")
	fmt.Println("  [gRPC Server] (handles HTTP/2, protobuf)")
	fmt.Println("       |")
	fmt.Println("       v")
	fmt.Println("  [Interceptors] (optional middleware)")
	fmt.Println("       |")
	fmt.Println("       v")
	fmt.Println("  [Service Implementation] (your business logic)")
	fmt.Println()

	fmt.Println("--- gRPC Status Codes (most common) ---")
	fmt.Println()
	fmt.Printf("  %-20s %s\n", "OK (0)", "Success")
	fmt.Printf("  %-20s %s\n", "Cancelled (1)", "Client cancelled the request")
	fmt.Printf("  %-20s %s\n", "InvalidArgument (3)", "Bad request from client")
	fmt.Printf("  %-20s %s\n", "NotFound (5)", "Requested resource not found")
	fmt.Printf("  %-20s %s\n", "AlreadyExists (6)", "Resource already exists")
	fmt.Printf("  %-20s %s\n", "PermissionDenied (7)", "Caller lacks permission")
	fmt.Printf("  %-20s %s\n", "Internal (13)", "Internal server error")
	fmt.Printf("  %-20s %s\n", "Unavailable (14)", "Service temporarily unavailable")
	fmt.Printf("  %-20s %s\n", "Unauthenticated (16)", "Missing or invalid auth")
	fmt.Println()

	// ========================================
	// Step 4: Start serving
	// ========================================
	fmt.Printf("gRPC server starting on %s\n", port)
	fmt.Println("Press Ctrl+C to stop.")
	fmt.Println()
	fmt.Println("To test with grpcurl (install: brew install grpcurl):")
	fmt.Println("  grpcurl -plaintext localhost:50051 list")
	fmt.Println("  grpcurl -plaintext -d '{\"name\":\"Test\",\"email\":\"t@t.com\"}' localhost:50051 user.UserService/CreateUser")

	// Serve blocks and handles incoming RPCs.
	// It returns only when Stop() or GracefulStop() is called.
	if err := grpcServer.Serve(lis); err != nil {
		log.Fatalf("Failed to serve: %v", err)
	}
}
